site_name: darpi
theme:
  name: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          heading_level: 2
          show_docstring_functions: false
          show_root_heading: true
          show_root_full_path: false
          show_source: true
          show_bases: true
- mkdocs-jupyter:
    execute: true
# nav:
#   - Home: index.md
#   - Examples: 
#     - Single Risk: single-risk.md
#     - Multiple Risks: multiple-risks.md
#     - Heat Maps: heat-maps.md
#   - Reference:
#     - Quantitative: 
#       - Probability: quantitative_probability.md
#       - Plots: quantitative_plots.md
#       - Tables: quantitative_tables.md
#     - Qualitative: 
#       - Probability: qualitative_probability.md
#       - Plots: qualitative_plots.md
#       - Tables: qualitative_tables.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences