site_name: darpi
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    view: material/eye
    edit: material/pencil
  features:
    - content.action.view
    - content.action.edit
repo_url: https://github.com/konnerhorton/darpi
repo_name: konnerhorton/darpi
edit_uri: tree/main/docs
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          heading_level: 2
          show_docstring_functions: false
          show_root_heading: true
          show_root_full_path: false
          show_source: true
          show_bases: true
- mkdocs-jupyter:
    execute: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  