"""Seed script: creates 200 risks and 50 mitigations for a metro tunnel mega-project.
Performance demo — no comments or proposals."""

import httpx

BASE = "http://localhost:8000/api/v1"

# ── 200 Risks across 8 categories (~25 each) ────────────────────────

RISKS = [
    # ── Tunneling (25) ───────────────────────────────────────────────
    {"title": "TBM breakdown at chainage 4+200", "description": "Tunnel boring machine main bearing failure requiring in-tunnel repair.", "category": "Tunneling", "probability": 20, "cost_min": 5_000_000, "cost_expected": 12_000_000, "cost_max": 25_000_000, "notes": "Manufacturer lead time for bearing is 14 weeks."},
    {"title": "Mixed-face tunneling conditions", "description": "Transition zone between rock and soft ground causing TBM instability and slower advance.", "category": "Tunneling", "probability": 55, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 15_000_000, "notes": "Geotechnical baseline report identifies three transition zones."},
    {"title": "Groundwater inflow exceeds pumping capacity", "description": "Unexpected aquifer connection flooding tunnel face beyond designed dewatering system.", "category": "Tunneling", "probability": 30, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Piezometer readings at BH-42 trending upward."},
    {"title": "Tunnel alignment deviation", "description": "TBM guidance system drift requiring correction grouting and segment replacement.", "category": "Tunneling", "probability": 15, "cost_min": 1_000_000, "cost_expected": 3_500_000, "cost_max": 8_000_000, "notes": "Survey control points to be established every 100m."},
    {"title": "Segmental lining damage during erection", "description": "Precast segment cracking from erector malfunction or mishandling.", "category": "Tunneling", "probability": 45, "cost_min": 500_000, "cost_expected": 2_000_000, "cost_max": 5_000_000, "notes": "Spare segment inventory policy under review."},
    {"title": "Hyperbaric intervention delays", "description": "Pressurized face interventions taking longer than planned due to ground conditions.", "category": "Tunneling", "probability": 35, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Certified hyperbaric crews limited in region."},
    {"title": "Spoil disposal site capacity", "description": "Designated muck disposal sites reaching capacity earlier than projected.", "category": "Tunneling", "probability": 40, "cost_min": 800_000, "cost_expected": 2_500_000, "cost_max": 6_000_000, "notes": "Two backup sites identified but not yet permitted."},
    {"title": "Cutter head tool wear — abrasive rock", "description": "Higher-than-expected disc cutter consumption in quartzite formation.", "category": "Tunneling", "probability": 50, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Cerchar abrasivity index results pending."},
    {"title": "Annular grout quality issues", "description": "Tail void grouting not achieving required strength, risking surface settlement.", "category": "Tunneling", "probability": 25, "cost_single": 1_500_000, "notes": "Mix design trials ongoing at materials lab."},
    {"title": "Cross-passage construction delays", "description": "Hand-mined cross-passages encountering worse ground than anticipated.", "category": "Tunneling", "probability": 45, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 12_000_000, "notes": "Ground freezing planned for two of six cross-passages."},
    {"title": "TBM launch shaft complications", "description": "Sheet pile deflection and base heave during shaft excavation.", "category": "Tunneling", "probability": 30, "cost_min": 1_500_000, "cost_expected": 4_500_000, "cost_max": 10_000_000, "notes": "Instrumentation monitoring plan in place."},
    {"title": "Tunnel ventilation during construction", "description": "Insufficient fresh air supply at extended drive lengths affecting worker safety.", "category": "Tunneling", "probability": 20, "cost_single": 2_000_000, "notes": "Ventilation ducting procurement on critical path."},
    {"title": "Probe drilling methane detection", "description": "Encountering methane pockets requiring additional safety protocols and slow advance.", "category": "Tunneling", "probability": 25, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Gas monitoring equipment specified in TBM order."},
    {"title": "Segment gasket failure at high water pressure", "description": "Hydrophilic gaskets not performing at pressures exceeding 3 bar.", "category": "Tunneling", "probability": 15, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 11_000_000, "notes": "Prototype testing at ETH Zurich lab complete."},
    {"title": "TBM retrieval shaft access constraints", "description": "Limited surface access for TBM disassembly and removal at reception shaft.", "category": "Tunneling", "probability": 35, "cost_single": 3_000_000, "notes": "Site surrounded by active rail corridor."},
    {"title": "Muck car derailment in tunnel", "description": "Rail-based spoil removal system experiencing frequent derailments on curved alignment.", "category": "Tunneling", "probability": 40, "cost_single": 800_000, "notes": "Minimum curve radius 250m at two locations."},
    {"title": "Bentonite slurry system malfunction", "description": "Slurry treatment plant downtime causing TBM face pressure loss.", "category": "Tunneling", "probability": 20, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 4_000_000, "notes": "Redundant pumps specified but single separation plant."},
    {"title": "Tunnel boring through old foundation piles", "description": "Unknown timber and concrete piles from demolished structures in TBM path.", "category": "Tunneling", "probability": 30, "cost_min": 1_000_000, "cost_expected": 3_500_000, "cost_max": 8_000_000, "notes": "Historical survey of demolished structures along alignment underway."},
    {"title": "Precast segment production delays", "description": "Casting yard quality issues or capacity constraints delaying ring delivery.", "category": "Tunneling", "probability": 25, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Two casting yards qualified — primary and backup."},
    {"title": "Secondary lining concrete placement", "description": "Formwork and concrete placement for secondary lining in tight tunnel geometry.", "category": "Tunneling", "probability": 35, "cost_single": 2_500_000, "notes": "Specialized travelling forms being designed."},
    {"title": "Tunnel waterproofing membrane installation", "description": "Sheet membrane installation defects leading to water ingress post-completion.", "category": "Tunneling", "probability": 30, "cost_min": 1_000_000, "cost_expected": 2_500_000, "cost_max": 6_000_000, "notes": "Third-party QA inspector assigned full-time."},
    {"title": "Convergence monitoring exceedance", "description": "Tunnel deformation exceeding trigger levels near existing structures.", "category": "Tunneling", "probability": 20, "cost_min": 3_000_000, "cost_expected": 7_000_000, "cost_max": 15_000_000, "notes": "Real-time monitoring linked to automated alerts."},
    {"title": "Compressed air working restrictions", "description": "Regulatory limits on hyperbaric exposure reducing available work windows.", "category": "Tunneling", "probability": 40, "cost_single": 1_800_000, "notes": "Medical screening for all tunnel crews mandatory."},
    {"title": "Emergency refuge chamber compliance", "description": "Updated safety regulations requiring additional refuge chambers not in original design.", "category": "Tunneling", "probability": 15, "cost_single": 900_000, "notes": "Regulation change effective next fiscal year."},
    {"title": "TBM cutterhead refurbishment", "description": "Mid-drive refurbishment needed earlier than planned due to mixed ground wear.", "category": "Tunneling", "probability": 35, "cost_min": 2_000_000, "cost_expected": 4_500_000, "cost_max": 9_000_000, "notes": "Intervention chamber design allows cutterhead access."},

    # ── Stations (25) ────────────────────────────────────────────────
    {"title": "Station cavern rock support failure", "description": "Rock bolts and shotcrete not performing in weathered zone above station cavern.", "category": "Stations", "probability": 20, "cost_min": 5_000_000, "cost_expected": 12_000_000, "cost_max": 25_000_000, "notes": "Additional probe holes recommended by geotechnical advisor."},
    {"title": "Escalator shaft excavation instability", "description": "Soil-rock interface at escalator shaft causing face collapse during sequential excavation.", "category": "Stations", "probability": 30, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Pipe umbrella support method planned."},
    {"title": "Platform edge door procurement delay", "description": "Platform screen door supplier unable to meet delivery schedule.", "category": "Stations", "probability": 35, "cost_single": 3_500_000, "notes": "Single-source supplier — exploring alternatives."},
    {"title": "Station architectural finish upgrade", "description": "Transit authority requesting higher-spec finishes at flagship stations mid-construction.", "category": "Stations", "probability": 50, "cost_min": 4_000_000, "cost_expected": 8_000_000, "cost_max": 15_000_000, "notes": "Public pressure for signature architecture at downtown stations."},
    {"title": "Fire life safety system integration", "description": "Complex integration of ventilation, detection, and suppression systems across five stations.", "category": "Stations", "probability": 55, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 12_000_000, "notes": "Fire engineer review of preliminary design pending."},
    {"title": "Station waterproofing failures", "description": "Cut-and-cover station box joints leaking under hydrostatic pressure.", "category": "Stations", "probability": 40, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Tanked waterproofing system specified."},
    {"title": "Passenger elevator installation delays", "description": "Elevator shaft dimensions conflicting with structural elements requiring redesign.", "category": "Stations", "probability": 25, "cost_single": 2_200_000, "notes": "Coordination between structural and vertical transport consultants."},
    {"title": "Station entrance canopy redesign", "description": "Wind load analysis requiring heavier steel sections for surface entrance canopies.", "category": "Stations", "probability": 30, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 3_500_000, "notes": "Wind tunnel testing scheduled."},
    {"title": "Concourse level slab pour complications", "description": "Large-area concrete pours at concourse level risking thermal cracking.", "category": "Stations", "probability": 35, "cost_single": 1_800_000, "notes": "Pour sequence and cooling pipe strategy under development."},
    {"title": "Station MEP coordination clashes", "description": "Mechanical, electrical, and plumbing routing conflicts in constrained station ceiling space.", "category": "Stations", "probability": 65, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "BIM clash detection running weekly."},
    {"title": "ADA compliance gap in station design", "description": "Accessibility review finding non-compliant path of travel at two stations.", "category": "Stations", "probability": 25, "cost_min": 1_000_000, "cost_expected": 2_500_000, "cost_max": 5_000_000, "notes": "Independent accessibility audit scheduled for next quarter."},
    {"title": "Station diaphragm wall panel misalignment", "description": "Diaphragm wall panels deviating from vertical tolerances during installation.", "category": "Stations", "probability": 20, "cost_min": 2_000_000, "cost_expected": 5_500_000, "cost_max": 12_000_000, "notes": "Ultrasonic testing after each panel pour."},
    {"title": "Ticket vending equipment obsolescence", "description": "Specified fare collection hardware reaching end-of-life before system commissioning.", "category": "Stations", "probability": 30, "cost_single": 4_000_000, "notes": "Technology refresh cycle 3 years — project timeline 5 years."},
    {"title": "Station HVAC ductwork space constraints", "description": "Ventilation duct routing requiring larger plenum spaces than allocated.", "category": "Stations", "probability": 45, "cost_min": 800_000, "cost_expected": 2_200_000, "cost_max": 5_000_000, "notes": "Computational fluid dynamics analysis in progress."},
    {"title": "Emergency egress stairway width deficiency", "description": "Fire modeling showing inadequate stair width for peak-hour evacuation scenarios.", "category": "Stations", "probability": 20, "cost_min": 3_000_000, "cost_expected": 7_000_000, "cost_max": 14_000_000, "notes": "Agent-based evacuation simulation commissioned."},
    {"title": "Station artwork and wayfinding coordination", "description": "Public art installations conflicting with signage sightlines and emergency lighting.", "category": "Stations", "probability": 40, "cost_single": 600_000, "notes": "Art commission and operations team not yet aligned on placement."},
    {"title": "Temporary station decking failure", "description": "Street-level decking over cut-and-cover excavation developing excessive deflection.", "category": "Stations", "probability": 15, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 8_000_000, "notes": "Independent structural review of decking design underway."},
    {"title": "Station utility connections delay", "description": "Power, water, and telecom service connections not ready for systems testing.", "category": "Stations", "probability": 50, "cost_single": 2_800_000, "notes": "Utility companies require 18 months lead time."},
    {"title": "Noise and vibration at station openings", "description": "Predicted noise levels at surface openings exceeding community standards.", "category": "Stations", "probability": 35, "cost_min": 500_000, "cost_expected": 1_800_000, "cost_max": 4_000_000, "notes": "Acoustic consultant engaged for mitigation options."},
    {"title": "Station structural steel erection tolerance", "description": "Long-span roof trusses at mezzanine level exceeding erection tolerances.", "category": "Stations", "probability": 25, "cost_single": 1_200_000, "notes": "Trial erection at fabrication yard planned."},
    {"title": "Back-of-house room allocation disputes", "description": "Operations, maintenance, and police all requesting more space than allocated.", "category": "Stations", "probability": 55, "cost_min": 400_000, "cost_expected": 1_200_000, "cost_max": 3_000_000, "notes": "Space allocation workshop scheduled with all stakeholders."},
    {"title": "Station dewatering system maintenance", "description": "Permanent dewatering pumps requiring more maintenance than budgeted.", "category": "Stations", "probability": 30, "cost_single": 900_000, "notes": "O&M cost model being updated."},
    {"title": "Retail space fitout coordination", "description": "Third-party retail tenant fitout interfering with station commissioning.", "category": "Stations", "probability": 35, "cost_single": 700_000, "notes": "Lease agreements need construction coordination clauses."},
    {"title": "Station CCTV and security system scope growth", "description": "Security requirements expanding post-design due to updated threat assessment.", "category": "Stations", "probability": 45, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 6_000_000, "notes": "Threat assessment update expected Q3."},
    {"title": "Station foundation settlement", "description": "Differential settlement between station box and adjacent structures.", "category": "Stations", "probability": 20, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 13_000_000, "notes": "Settlement monitoring baseline established."},

    # ── Utilities (25) ───────────────────────────────────────────────
    {"title": "High-voltage cable relocation", "description": "132kV transmission line requiring diversion around station box excavation.", "category": "Utilities", "probability": 60, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Power utility approval process takes 12+ months."},
    {"title": "Gas main proximity to tunnel alignment", "description": "High-pressure gas main within 2m of tunnel crown requiring protection or diversion.", "category": "Utilities", "probability": 35, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 11_000_000, "notes": "Gas utility insisting on diversion — negotiating protection alternative."},
    {"title": "Sewer trunk line conflict at Station 3", "description": "1800mm combined sewer crossing station footprint at concourse level.", "category": "Utilities", "probability": 70, "cost_min": 4_000_000, "cost_expected": 10_000_000, "cost_max": 20_000_000, "notes": "Sewer diversion design at 30% — complex tie-in to existing system."},
    {"title": "Unknown utilities discovery", "description": "Uncharted utilities found during excavation causing work stoppages.", "category": "Utilities", "probability": 65, "cost_min": 1_000_000, "cost_expected": 4_000_000, "cost_max": 10_000_000, "notes": "GPR and vacuum potholing program planned but not complete."},
    {"title": "Water main break during construction", "description": "Aging cast iron water mains breaking from construction vibration.", "category": "Utilities", "probability": 40, "cost_min": 500_000, "cost_expected": 2_000_000, "cost_max": 5_000_000, "notes": "Water utility providing condition assessment data."},
    {"title": "Telecom fiber optic relocation", "description": "Multiple carrier fiber bundles requiring coordinated relocation.", "category": "Utilities", "probability": 50, "cost_single": 3_500_000, "notes": "Four carriers affected — coordination agreement not yet signed."},
    {"title": "District heating pipe conflict", "description": "Steam distribution pipes crossing alignment at shallow depth.", "category": "Utilities", "probability": 25, "cost_min": 1_500_000, "cost_expected": 3_500_000, "cost_max": 7_000_000, "notes": "Thermal insulation requirements complicate relocation."},
    {"title": "Stormwater system capacity exceedance", "description": "Existing storm drains unable to handle redirected flows during construction.", "category": "Utilities", "probability": 35, "cost_min": 800_000, "cost_expected": 2_500_000, "cost_max": 6_000_000, "notes": "Hydraulic model of impacted catchment area being built."},
    {"title": "Utility survey data inaccuracy", "description": "As-built records from 1960s-era utility installations significantly inaccurate.", "category": "Utilities", "probability": 55, "cost_single": 1_800_000, "notes": "Field verification program 40% complete."},
    {"title": "Power supply for TBM — grid capacity", "description": "Local electrical grid unable to supply 5MW peak demand for TBM operations.", "category": "Utilities", "probability": 30, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Grid reinforcement lead time 18 months."},
    {"title": "Temporary utility bypass failures", "description": "Temporary pipes and cables installed for utility diversions failing under load.", "category": "Utilities", "probability": 25, "cost_min": 400_000, "cost_expected": 1_200_000, "cost_max": 3_000_000, "notes": "Design life of temporary works under review."},
    {"title": "Third-party utility damage claims", "description": "Adjacent utility owners claiming construction-related damage and seeking compensation.", "category": "Utilities", "probability": 45, "cost_min": 1_000_000, "cost_expected": 3_500_000, "cost_max": 8_000_000, "notes": "Pre-construction condition surveys of all adjacent utilities underway."},
    {"title": "Utility reinstatement to higher standard", "description": "Utility owners requiring replacement to current code rather than like-for-like.", "category": "Utilities", "probability": 50, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Negotiating cost-sharing for betterment component."},
    {"title": "Contaminated soil at utility excavations", "description": "Hazardous materials found around old utility trenches requiring special disposal.", "category": "Utilities", "probability": 35, "cost_min": 600_000, "cost_expected": 2_000_000, "cost_max": 5_000_000, "notes": "Environmental contingency included but may be insufficient."},
    {"title": "Utility protection slab design changes", "description": "Concrete protection slabs for retained utilities needing redesign for heavier loads.", "category": "Utilities", "probability": 30, "cost_single": 1_100_000, "notes": "Geotechnical review of surcharge loads in progress."},
    {"title": "Electrical substation relocation", "description": "Distribution substation in station footprint requiring temporary and permanent relocation.", "category": "Utilities", "probability": 40, "cost_min": 3_000_000, "cost_expected": 7_000_000, "cost_max": 14_000_000, "notes": "Site identified for permanent relocation — land acquisition pending."},
    {"title": "Fire hydrant relocation and coverage gaps", "description": "Construction zones eliminating fire hydrant coverage requiring temporary replacements.", "category": "Utilities", "probability": 55, "cost_single": 400_000, "notes": "Fire department requires maintained coverage at all times."},
    {"title": "Utility monitoring instrumentation", "description": "Real-time monitoring of retained utilities costing more than budgeted.", "category": "Utilities", "probability": 30, "cost_single": 650_000, "notes": "Fiber optic strain gauges specified for critical utilities."},
    {"title": "Joint utility trench construction", "description": "New combined utility corridor requiring coordination between five utility owners.", "category": "Utilities", "probability": 45, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 8_000_000, "notes": "Multi-party agreement being drafted by legal team."},
    {"title": "Utility easement acquisition", "description": "New permanent easements required for relocated utilities on private property.", "category": "Utilities", "probability": 40, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Property owners notified — negotiations starting."},
    {"title": "Dewatering discharge permit constraints", "description": "Environmental agency restricting groundwater discharge volumes and quality thresholds.", "category": "Utilities", "probability": 35, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 4_000_000, "notes": "Treatment plant sizing based on preliminary water quality data."},
    {"title": "Emergency power generation for utilities", "description": "Backup generators needed during utility switchovers to prevent service outages.", "category": "Utilities", "probability": 20, "cost_single": 800_000, "notes": "Generator fleet availability confirmed with rental company."},
    {"title": "Cathodic protection system interference", "description": "Stray current from tunnel systems affecting cathodic protection on adjacent gas mains.", "category": "Utilities", "probability": 25, "cost_single": 500_000, "notes": "Stray current study commissioned."},
    {"title": "Utility freeze protection during winter work", "description": "Exposed water mains at risk of freezing during winter construction phases.", "category": "Utilities", "probability": 30, "cost_single": 350_000, "notes": "Temporary insulation and heat tracing planned."},
    {"title": "Traffic signal and ITS relocation", "description": "Intelligent transportation system cabinets and conduit in construction zone.", "category": "Utilities", "probability": 45, "cost_min": 300_000, "cost_expected": 900_000, "cost_max": 2_000_000, "notes": "City DOT coordination meetings biweekly."},

    # ── Design (25) ──────────────────────────────────────────────────
    {"title": "Geotechnical baseline report disputes", "description": "Contractor claiming changed conditions based on GBR interpretation differences.", "category": "Design", "probability": 60, "cost_min": 5_000_000, "cost_expected": 15_000_000, "cost_max": 35_000_000, "notes": "Independent geotechnical review of GBR language underway."},
    {"title": "Seismic design criteria update", "description": "Updated seismic hazard maps requiring structural redesign of underground structures.", "category": "Design", "probability": 25, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "New maps published — impact assessment in progress."},
    {"title": "Design package coordination gaps", "description": "Interface issues between civil, structural, and systems design packages.", "category": "Design", "probability": 55, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 12_000_000, "notes": "Design interface register being compiled."},
    {"title": "Track alignment optimization", "description": "Late changes to horizontal and vertical track alignment affecting civil structures.", "category": "Design", "probability": 35, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Track geometry review with operations team pending."},
    {"title": "Structural design code change", "description": "New edition of concrete design code published during detailed design phase.", "category": "Design", "probability": 20, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Transition provisions being reviewed with building authority."},
    {"title": "Ventilation shaft design — urban constraints", "description": "Surface ventilation structures conflicting with city streetscape requirements.", "category": "Design", "probability": 45, "cost_min": 800_000, "cost_expected": 2_500_000, "cost_max": 6_000_000, "notes": "Urban design panel review required."},
    {"title": "Fire engineering peer review findings", "description": "Independent fire engineer identifying deficiencies in fire strategy.", "category": "Design", "probability": 40, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 8_000_000, "notes": "Peer review report expected in 6 weeks."},
    {"title": "Tunnel lining thickness increase", "description": "Ground conditions requiring thicker segmental lining than designed.", "category": "Design", "probability": 20, "cost_min": 4_000_000, "cost_expected": 10_000_000, "cost_max": 22_000_000, "notes": "Affects segment mould redesign and TBM tail seal."},
    {"title": "Sustainability certification requirements", "description": "New sustainability framework imposing additional design and material requirements.", "category": "Design", "probability": 35, "cost_single": 2_500_000, "notes": "LEED and Envision credits being tracked."},
    {"title": "Design-build interface coordination", "description": "Misalignment between reference design and contractor's detailed design approach.", "category": "Design", "probability": 50, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 16_000_000, "notes": "Design management plan under negotiation."},
    {"title": "Constructability review findings", "description": "Late constructability issues requiring design changes after bid documents issued.", "category": "Design", "probability": 45, "cost_min": 1_000_000, "cost_expected": 3_500_000, "cost_max": 8_000_000, "notes": "Contractor constructability workshop scheduled."},
    {"title": "BIM model accuracy for construction", "description": "Design BIM models not at sufficient LOD for construction use.", "category": "Design", "probability": 40, "cost_single": 1_800_000, "notes": "LOD 400 required — current models at LOD 300."},
    {"title": "Drainage design capacity shortfall", "description": "Tunnel and station drainage systems undersized for projected climate change flows.", "category": "Design", "probability": 30, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Climate resilience review incorporating 2080 projections."},
    {"title": "Noise and vibration prediction model error", "description": "Operational noise predictions underestimating impact on sensitive receptors.", "category": "Design", "probability": 25, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Floating slab track may be required at additional locations."},
    {"title": "Emergency walkway width non-compliance", "description": "Tunnel emergency walkway not meeting updated evacuation code requirements.", "category": "Design", "probability": 15, "cost_min": 3_000_000, "cost_expected": 7_000_000, "cost_max": 15_000_000, "notes": "Code change would require tunnel diameter increase."},
    {"title": "Third-party design review delays", "description": "External review agencies taking longer than planned to approve design submissions.", "category": "Design", "probability": 55, "cost_single": 2_200_000, "notes": "Four separate review agencies involved."},
    {"title": "Foundation design — adjacent buildings", "description": "Additional underpinning needed for buildings closer to excavation than initially assessed.", "category": "Design", "probability": 30, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 14_000_000, "notes": "Building condition surveys 80% complete."},
    {"title": "Systems integration design complexity", "description": "Train control, communications, and SCADA system interface design proving more complex than estimated.", "category": "Design", "probability": 50, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 11_000_000, "notes": "Systems integrator design review at 60%."},
    {"title": "Geotechnical instrumentation specification gap", "description": "Monitoring instruments not specified for all critical zones.", "category": "Design", "probability": 25, "cost_single": 750_000, "notes": "Instrumentation plan being expanded."},
    {"title": "Permanent way design — switch and crossing", "description": "Complex trackwork at junction requiring bespoke design and long-lead procurement.", "category": "Design", "probability": 35, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 8_000_000, "notes": "Supplier design input needed early."},
    {"title": "Architectural treatment at portals", "description": "Tunnel portal design not yet approved by heritage conservation authority.", "category": "Design", "probability": 30, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 3_500_000, "notes": "Heritage impact assessment submitted."},
    {"title": "Stray current protection design", "description": "DC traction system stray current mitigation requiring additional design measures.", "category": "Design", "probability": 40, "cost_single": 1_200_000, "notes": "Stray current modeling contract awarded."},
    {"title": "Value engineering savings not achievable", "description": "Assumed VE savings from preliminary design phase proving unrealistic in detail design.", "category": "Design", "probability": 45, "cost_min": 5_000_000, "cost_expected": 12_000_000, "cost_max": 25_000_000, "notes": "$40M VE target set during business case — $28M identified so far."},
    {"title": "Specification conflicts between disciplines", "description": "Contradictory material and performance specs between civil and systems packages.", "category": "Design", "probability": 35, "cost_single": 900_000, "notes": "Specification harmonization review in progress."},
    {"title": "Durability design for 120-year life", "description": "Enhanced durability requirements for underground structures increasing material costs.", "category": "Design", "probability": 50, "cost_min": 3_000_000, "cost_expected": 7_000_000, "cost_max": 14_000_000, "notes": "Chloride ingress modeling for all exposed concrete."},

    # ── Geotechnical (25) ────────────────────────────────────────────
    {"title": "Unexpected fault zone crossing", "description": "Previously unidentified geological fault intersecting tunnel alignment.", "category": "Geotechnical", "probability": 15, "cost_min": 8_000_000, "cost_expected": 20_000_000, "cost_max": 45_000_000, "notes": "Seismic refraction survey planned along alignment."},
    {"title": "Karst features in limestone formation", "description": "Solution cavities and voids in limestone requiring treatment before tunneling.", "category": "Geotechnical", "probability": 25, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Borehole camera surveys in karst zone complete."},
    {"title": "High groundwater pressure at depth", "description": "Artesian groundwater conditions at tunnel depth exceeding design assumptions.", "category": "Geotechnical", "probability": 30, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 14_000_000, "notes": "Packer testing results at deep boreholes being analyzed."},
    {"title": "Soft clay squeezing ground", "description": "Thick marine clay layer causing long-term convergence pressures on tunnel lining.", "category": "Geotechnical", "probability": 35, "cost_min": 4_000_000, "cost_expected": 10_000_000, "cost_max": 20_000_000, "notes": "Consolidation testing on undisturbed samples underway."},
    {"title": "Boulder field in glacial till", "description": "Oversized cobbles and boulders in glacial deposits causing TBM obstruction.", "category": "Geotechnical", "probability": 45, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Historical quarry records indicate cobble-rich deposits."},
    {"title": "Ground settlement affecting surface structures", "description": "TBM-induced settlement exceeding trigger levels for buildings and utilities.", "category": "Geotechnical", "probability": 40, "cost_min": 3_000_000, "cost_expected": 9_000_000, "cost_max": 22_000_000, "notes": "Greenfield settlement trough analysis complete — building risk assessments pending."},
    {"title": "Contaminated groundwater plume", "description": "Migrating contamination plume from industrial site intercepting dewatering zone.", "category": "Geotechnical", "probability": 20, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 12_000_000, "notes": "Environmental baseline monitoring wells installed."},
    {"title": "Expansive clay minerals", "description": "Swelling ground pressures from montmorillonite-rich clay affecting station structures.", "category": "Geotechnical", "probability": 25, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Swell pressure testing on samples from BH-15 through BH-22."},
    {"title": "Residual soil variability", "description": "Highly variable residual soil properties requiring adaptive ground support design.", "category": "Geotechnical", "probability": 50, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Additional boreholes authorized to reduce uncertainty."},
    {"title": "Dewatering drawdown on adjacent structures", "description": "Dewatering-induced settlement causing damage to nearby buildings on shallow foundations.", "category": "Geotechnical", "probability": 30, "cost_min": 2_000_000, "cost_expected": 5_500_000, "cost_max": 12_000_000, "notes": "Pumping test planned to calibrate drawdown model."},
    {"title": "Slope stability at portal cut", "description": "Tunnel portal approach cut exceeding safe slope angles in residual soil.", "category": "Geotechnical", "probability": 20, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Soil nailing or anchored wall alternatives being evaluated."},
    {"title": "Perched water table at station excavation", "description": "Unexpected perched aquifer causing water ingress to station excavation.", "category": "Geotechnical", "probability": 35, "cost_single": 2_000_000, "notes": "Not identified in initial site investigation."},
    {"title": "Rock mass classification worse than expected", "description": "Actual rock mass quality lower than GBR characterization requiring heavier support.", "category": "Geotechnical", "probability": 40, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Additional rock core logging and RQD analysis."},
    {"title": "Ground improvement treatment ineffective", "description": "Jet grouting or ground freezing not achieving design strength.", "category": "Geotechnical", "probability": 25, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Trial treatment program included in early works contract."},
    {"title": "Soil gas emissions — radon and methane", "description": "Naturally occurring soil gases requiring additional ventilation and monitoring.", "category": "Geotechnical", "probability": 20, "cost_single": 800_000, "notes": "Soil gas survey results indicate low-to-moderate risk."},
    {"title": "Sinkhole development above tunnel", "description": "Localized ground collapse above tunnel from crown over-excavation or face instability.", "category": "Geotechnical", "probability": 10, "cost_min": 5_000_000, "cost_expected": 15_000_000, "cost_max": 35_000_000, "notes": "Real-time surface monitoring with InSAR planned."},
    {"title": "Artesian blowout at shaft base", "description": "High-pressure groundwater blowing through shaft base during excavation.", "category": "Geotechnical", "probability": 15, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Plug design being reviewed by specialist consultant."},
    {"title": "Lateral ground movement from adjacent construction", "description": "Neighboring development causing ground displacement affecting tunnel alignment.", "category": "Geotechnical", "probability": 20, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Coordination agreement with adjacent developer not yet finalized."},
    {"title": "Soil liquefaction potential", "description": "Loose saturated sands susceptible to liquefaction during seismic event.", "category": "Geotechnical", "probability": 10, "cost_min": 4_000_000, "cost_expected": 10_000_000, "cost_max": 22_000_000, "notes": "SPT and CPT results being analyzed for liquefaction susceptibility."},
    {"title": "Acid sulfate soil conditions", "description": "Excavation of acid sulfate soils requiring special handling and treatment.", "category": "Geotechnical", "probability": 30, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 4_000_000, "notes": "Acid sulfate soil management plan in preparation."},
    {"title": "Ground investigation data gaps", "description": "Insufficient borehole coverage in critical zones requiring supplementary investigation.", "category": "Geotechnical", "probability": 55, "cost_single": 1_200_000, "notes": "Phase 2 supplementary investigation scope being defined."},
    {"title": "Heave at deep excavation base", "description": "Base heave in soft clay at deep station excavation exceeding serviceability limits.", "category": "Geotechnical", "probability": 25, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 11_000_000, "notes": "Base slab construction sequence critical."},
    {"title": "Aggressive ground chemistry on concrete", "description": "Sulfate-bearing soils attacking concrete requiring enhanced protection measures.", "category": "Geotechnical", "probability": 35, "cost_min": 800_000, "cost_expected": 2_500_000, "cost_max": 6_000_000, "notes": "Sulfate-resisting cement specified — admixture testing underway."},
    {"title": "Buried channel deposits", "description": "Deep alluvial channel cutting through bedrock creating soft ground pocket.", "category": "Geotechnical", "probability": 20, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Geophysical survey data being reinterpreted."},
    {"title": "Rock hardness exceeding TBM specifications", "description": "UCS values higher than design envelope for TBM cutterhead capacity.", "category": "Geotechnical", "probability": 15, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 14_000_000, "notes": "Additional UCS testing from new cores pending."},

    # ── Community Impacts (25) ───────────────────────────────────────
    {"title": "Residential property damage claims", "description": "Pre-existing building damage attributed to construction vibration.", "category": "Community Impacts", "probability": 65, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 15_000_000, "notes": "Pre-construction surveys complete for 800+ properties."},
    {"title": "Business interruption claims", "description": "Commercial tenants claiming loss of trade from construction disruption.", "category": "Community Impacts", "probability": 55, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Business mitigation fund established but scope under review."},
    {"title": "Community opposition to ventilation shaft", "description": "Neighborhood group opposing surface ventilation facility near school.", "category": "Community Impacts", "probability": 50, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Community liaison officer assigned. Alternative locations being studied."},
    {"title": "Nightwork restrictions", "description": "Council imposing stricter nighttime construction noise limits than planned.", "category": "Community Impacts", "probability": 45, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Noise management plan under review by council."},
    {"title": "School zone construction timing constraints", "description": "Restrictions on heavy vehicle movements during school hours near three sites.", "category": "Community Impacts", "probability": 60, "cost_single": 1_500_000, "notes": "Traffic management plan incorporating school zone constraints."},
    {"title": "Heritage building protection costs", "description": "Additional protection measures for heritage-listed buildings near alignment.", "category": "Community Impacts", "probability": 40, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Heritage impact assessment identified 12 buildings."},
    {"title": "Community liaison staffing increase", "description": "More community engagement staff needed than budgeted to manage complaints.", "category": "Community Impacts", "probability": 50, "cost_single": 800_000, "notes": "Complaint volume 3x forecast in first quarter."},
    {"title": "Dust and air quality complaints", "description": "Construction dust exceeding EPA limits requiring additional mitigation.", "category": "Community Impacts", "probability": 55, "cost_min": 400_000, "cost_expected": 1_200_000, "cost_max": 3_000_000, "notes": "Dust monitors installed at all site boundaries."},
    {"title": "Traffic management plan revisions", "description": "Road authority requiring more complex traffic staging than originally planned.", "category": "Community Impacts", "probability": 65, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 8_000_000, "notes": "Third revision submitted — awaiting approval."},
    {"title": "Pedestrian access disruption claims", "description": "Disability advocacy groups challenging construction zone accessibility.", "category": "Community Impacts", "probability": 35, "cost_single": 600_000, "notes": "Accessible detour routes being designed."},
    {"title": "Religious institution noise complaint", "description": "Place of worship adjacent to shaft site requesting construction pauses.", "category": "Community Impacts", "probability": 30, "cost_single": 400_000, "notes": "Negotiating quiet hours agreement."},
    {"title": "Park and recreation space temporary loss", "description": "Public park used as construction staging area requiring restoration.", "category": "Community Impacts", "probability": 70, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 6_000_000, "notes": "Parks department agreement includes enhanced restoration."},
    {"title": "Local road pavement damage", "description": "Heavy construction vehicles degrading residential street pavement.", "category": "Community Impacts", "probability": 60, "cost_min": 800_000, "cost_expected": 2_500_000, "cost_max": 5_000_000, "notes": "Road condition surveys pre- and post-construction."},
    {"title": "Archaeological discovery", "description": "Previously unknown archaeological finds requiring investigation and potential redesign.", "category": "Community Impacts", "probability": 20, "cost_min": 1_000_000, "cost_expected": 4_000_000, "cost_max": 12_000_000, "notes": "Desktop archaeological assessment complete — moderate risk zone identified."},
    {"title": "Construction worker parking overflow", "description": "Worker vehicles overwhelming residential street parking near work sites.", "category": "Community Impacts", "probability": 45, "cost_single": 300_000, "notes": "Remote parking with shuttle service being evaluated."},
    {"title": "Tree removal and replacement costs", "description": "Mature tree removal requiring compensation planting at higher ratios than planned.", "category": "Community Impacts", "probability": 50, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 3_500_000, "notes": "Arborist assessment identified 45 significant trees."},
    {"title": "Groundborne noise in residential buildings", "description": "TBM-induced groundborne noise exceeding criteria in apartments above tunnel.", "category": "Community Impacts", "probability": 35, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Vibration monitoring during TBM approach."},
    {"title": "Emergency vehicle access constraints", "description": "Construction zones blocking emergency response routes requiring detours.", "category": "Community Impacts", "probability": 40, "cost_single": 500_000, "notes": "Fire and ambulance services consulted on traffic management."},
    {"title": "Media coverage of construction incidents", "description": "Negative media attention amplifying public opposition and political scrutiny.", "category": "Community Impacts", "probability": 55, "cost_single": 2_000_000, "notes": "Communications strategy and crisis plan in place."},
    {"title": "Environmental offset requirements", "description": "Regulatory agency requiring biodiversity offsets exceeding initial estimates.", "category": "Community Impacts", "probability": 30, "cost_min": 800_000, "cost_expected": 2_000_000, "cost_max": 5_000_000, "notes": "Flora and fauna surveys finalized."},
    {"title": "Vibration damage to underground infrastructure", "description": "Construction vibration affecting gas, water, and sewer pipes near work zones.", "category": "Community Impacts", "probability": 35, "cost_min": 600_000, "cost_expected": 2_000_000, "cost_max": 5_000_000, "notes": "Vibration limits agreed with utility owners."},
    {"title": "Public art relocation", "description": "Public sculptures and murals in construction zone requiring careful removal and storage.", "category": "Community Impacts", "probability": 25, "cost_single": 350_000, "notes": "Art conservation specialist engaged."},
    {"title": "Taxi and rideshare staging disruption", "description": "Construction eliminating designated pickup/dropoff zones at major intersections.", "category": "Community Impacts", "probability": 40, "cost_single": 250_000, "notes": "Temporary staging areas being identified."},
    {"title": "Noise barrier installation requirements", "description": "Sound walls needed at more locations than planned based on noise monitoring data.", "category": "Community Impacts", "probability": 50, "cost_min": 600_000, "cost_expected": 1_800_000, "cost_max": 4_000_000, "notes": "Noise monitoring results from first month of construction."},
    {"title": "Stormwater runoff from construction sites", "description": "Sediment-laden runoff reaching waterways despite erosion controls.", "category": "Community Impacts", "probability": 30, "cost_min": 300_000, "cost_expected": 900_000, "cost_max": 2_500_000, "notes": "Enhanced sediment basins being designed."},

    # ── System Integration (25) ──────────────────────────────────────
    {"title": "Signaling system delivery delay", "description": "CBTC supplier behind schedule on software development and factory testing.", "category": "System Integration", "probability": 55, "cost_min": 5_000_000, "cost_expected": 15_000_000, "cost_max": 30_000_000, "notes": "Monthly progress reviews showing 3-month delay trend."},
    {"title": "Rolling stock and platform interface", "description": "Gap and step between train and platform exceeding accessibility standards.", "category": "System Integration", "probability": 30, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Dynamic envelope analysis in progress."},
    {"title": "Traction power system capacity shortfall", "description": "Traction substations undersized for peak service headway operations.", "category": "System Integration", "probability": 25, "cost_min": 4_000_000, "cost_expected": 10_000_000, "cost_max": 20_000_000, "notes": "Power flow simulation with updated train performance data."},
    {"title": "SCADA system integration complexity", "description": "Supervisory control system interfaces with 15+ subsystems proving difficult to integrate.", "category": "System Integration", "probability": 50, "cost_min": 2_000_000, "cost_expected": 6_000_000, "cost_max": 12_000_000, "notes": "Integration testing schedule compressed."},
    {"title": "Communications backbone redundancy gap", "description": "Fiber optic backbone lacks sufficient redundancy for operational resilience.", "category": "System Integration", "probability": 35, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Alternative routing through tunnel bore being evaluated."},
    {"title": "Tunnel ventilation fan procurement delay", "description": "Jet fan supplier lead time extending beyond construction schedule requirement.", "category": "System Integration", "probability": 40, "cost_single": 2_500_000, "notes": "Alternative suppliers being pre-qualified."},
    {"title": "Track circuit interference", "description": "Electromagnetic interference from traction power affecting track circuit reliability.", "category": "System Integration", "probability": 30, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 8_000_000, "notes": "EMC study commissioned."},
    {"title": "Depot systems integration", "description": "Maintenance depot systems not integrating with mainline train control.", "category": "System Integration", "probability": 40, "cost_min": 1_000_000, "cost_expected": 3_500_000, "cost_max": 8_000_000, "notes": "Depot control system RFP issued."},
    {"title": "Platform screen door and train door alignment", "description": "PSDs not aligning consistently with train doors across fleet variants.", "category": "System Integration", "probability": 35, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Stopping accuracy specification under review."},
    {"title": "Fare collection system integration", "description": "Fare gates and backend system not integrating with regional transit smart card.", "category": "System Integration", "probability": 45, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Regional transit authority API documentation incomplete."},
    {"title": "Emergency telephone system coverage gaps", "description": "Help points and emergency phones not covering all required locations.", "category": "System Integration", "probability": 20, "cost_single": 600_000, "notes": "Coverage analysis being updated."},
    {"title": "Passenger information display integration", "description": "Real-time displays not receiving data from train control system.", "category": "System Integration", "probability": 35, "cost_single": 1_200_000, "notes": "Data feed protocol mismatch identified."},
    {"title": "UPS and battery backup sizing", "description": "Uninterruptible power supply systems undersized for actual connected loads.", "category": "System Integration", "probability": 30, "cost_min": 800_000, "cost_expected": 2_000_000, "cost_max": 5_000_000, "notes": "Load audit revealing scope growth since preliminary design."},
    {"title": "Train-to-wayside communication dropouts", "description": "Radio coverage dead zones in tunnel causing communication blackouts.", "category": "System Integration", "probability": 40, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 6_000_000, "notes": "Leaky feeder cable specification under review."},
    {"title": "Integrated testing and commissioning schedule", "description": "ITC phase compressed due to civil construction delays consuming float.", "category": "System Integration", "probability": 60, "cost_min": 5_000_000, "cost_expected": 12_000_000, "cost_max": 25_000_000, "notes": "ITC phase originally 18 months — now potentially 12 months."},
    {"title": "Cybersecurity compliance for OT systems", "description": "Operational technology systems not meeting updated cybersecurity framework.", "category": "System Integration", "probability": 35, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Cybersecurity assessment in progress."},
    {"title": "Earthing and bonding system coordination", "description": "Stray current collection and earthing systems between multiple contractors.", "category": "System Integration", "probability": 25, "cost_single": 1_500_000, "notes": "Earthing philosophy document in draft."},
    {"title": "Automatic train protection software bugs", "description": "Safety-critical software defects found during system integration testing.", "category": "System Integration", "probability": 45, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 16_000_000, "notes": "Independent safety assessor review included in schedule."},
    {"title": "Depot overhead crane installation", "description": "Crane runway beam alignment issues in maintenance depot.", "category": "System Integration", "probability": 20, "cost_single": 700_000, "notes": "Structural steel tolerances being verified."},
    {"title": "Public address system intelligibility", "description": "PA system speech transmission index below required levels in reverberant station spaces.", "category": "System Integration", "probability": 40, "cost_min": 500_000, "cost_expected": 1_500_000, "cost_max": 3_500_000, "notes": "Acoustic modeling for all station types."},
    {"title": "Third rail / OCS interface at depot", "description": "Transition between third rail in tunnel and overhead catenary at depot.", "category": "System Integration", "probability": 25, "cost_min": 800_000, "cost_expected": 2_000_000, "cost_max": 4_500_000, "notes": "Changeover zone design with rolling stock manufacturer."},
    {"title": "Tunnel lighting control system", "description": "Addressable lighting system not integrating with building management system.", "category": "System Integration", "probability": 30, "cost_single": 400_000, "notes": "Protocol mismatch between DALI and BACnet."},
    {"title": "Driverless operation readiness", "description": "GoA4 driverless operation requiring higher systems reliability than demonstrated.", "category": "System Integration", "probability": 50, "cost_min": 4_000_000, "cost_expected": 10_000_000, "cost_max": 20_000_000, "notes": "Reliability growth testing plan in development."},
    {"title": "Station mechanical ventilation control", "description": "Tunnel and station ventilation modes conflicting during emergency scenarios.", "category": "System Integration", "probability": 35, "cost_min": 800_000, "cost_expected": 2_500_000, "cost_max": 6_000_000, "notes": "Ventilation control philosophy under revision."},
    {"title": "Energy metering and billing system", "description": "Traction energy metering system not compatible with utility billing requirements.", "category": "System Integration", "probability": 20, "cost_single": 500_000, "notes": "Utility metering requirements recently changed."},

    # ── Program Management (25) ──────────────────────────────────────
    {"title": "Land acquisition delays", "description": "Compulsory acquisition of three remaining parcels facing legal challenges.", "category": "Program Management", "probability": 45, "cost_min": 5_000_000, "cost_expected": 15_000_000, "cost_max": 35_000_000, "notes": "Two landowners have filed objections."},
    {"title": "Federal funding conditions change", "description": "Grant conditions amended requiring additional project milestones and reporting.", "category": "Program Management", "probability": 30, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 12_000_000, "notes": "New administration reviewing all transit grants."},
    {"title": "Key personnel departure", "description": "Project director or chief engineer departing mid-project.", "category": "Program Management", "probability": 35, "cost_single": 3_000_000, "notes": "Succession plan not yet formalized."},
    {"title": "Insurance premium increase", "description": "Project insurance premiums rising at renewal due to claims history or market conditions.", "category": "Program Management", "probability": 40, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "Broker market sounding underway."},
    {"title": "Inflation exceeding escalation provisions", "description": "Construction cost inflation outpacing contract escalation formulas.", "category": "Program Management", "probability": 50, "cost_min": 10_000_000, "cost_expected": 25_000_000, "cost_max": 60_000_000, "notes": "CPI and PPI indices trending above escalation assumptions."},
    {"title": "Contract dispute — differing site conditions", "description": "Major claim from tunneling contractor for changed geotechnical conditions.", "category": "Program Management", "probability": 55, "cost_min": 8_000_000, "cost_expected": 20_000_000, "cost_max": 45_000_000, "notes": "Dispute review board appointed."},
    {"title": "Program schedule critical path delay", "description": "Multiple near-critical paths converging, creating schedule fragility.", "category": "Program Management", "probability": 60, "cost_min": 10_000_000, "cost_expected": 30_000_000, "cost_max": 70_000_000, "notes": "Schedule risk analysis update due next month."},
    {"title": "Earned value variance — cost overrun", "description": "CPI trending below 0.90 indicating systemic cost control issues.", "category": "Program Management", "probability": 45, "cost_min": 15_000_000, "cost_expected": 40_000_000, "cost_max": 80_000_000, "notes": "Corrective action plan being developed."},
    {"title": "Stakeholder approval delay — transit authority", "description": "Transit authority board approval processes taking longer than planned.", "category": "Program Management", "probability": 50, "cost_single": 4_000_000, "notes": "Board meetings quarterly — missed window delays 3 months."},
    {"title": "Environmental impact statement supplement", "description": "Design changes triggering supplemental environmental review.", "category": "Program Management", "probability": 25, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 12_000_000, "notes": "Alignment shift at Station 4 may trigger supplemental EIS."},
    {"title": "Contractor bonding capacity exhaustion", "description": "General contractor's surety capacity fully consumed limiting change order capacity.", "category": "Program Management", "probability": 20, "cost_single": 3_000_000, "notes": "Surety company monitoring contractor financial health."},
    {"title": "Force majeure — pandemic resurgence", "description": "Public health emergency restricting workforce density and supply chains.", "category": "Program Management", "probability": 15, "cost_min": 10_000_000, "cost_expected": 30_000_000, "cost_max": 70_000_000, "notes": "Pandemic response plan from previous experience available."},
    {"title": "Political intervention in project scope", "description": "Elected officials requesting additional station or alignment changes.", "category": "Program Management", "probability": 40, "cost_min": 20_000_000, "cost_expected": 50_000_000, "cost_max": 120_000_000, "notes": "Election cycle in 18 months — expect scope pressure."},
    {"title": "Foreign exchange on imported equipment", "description": "Currency fluctuation affecting cost of imported TBM, rolling stock, and systems.", "category": "Program Management", "probability": 45, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Partial hedging strategy in place."},
    {"title": "Multi-contract interface risk", "description": "Five major contracts with poorly defined interface responsibilities.", "category": "Program Management", "probability": 55, "cost_min": 3_000_000, "cost_expected": 10_000_000, "cost_max": 22_000_000, "notes": "Interface management plan being finalized."},
    {"title": "Contingency drawdown rate", "description": "Project contingency being consumed faster than forecast.", "category": "Program Management", "probability": 50, "cost_min": 5_000_000, "cost_expected": 15_000_000, "cost_max": 35_000_000, "notes": "Monthly contingency tracking dashboard established."},
    {"title": "Workforce skills shortage — systems", "description": "Insufficient local workforce for specialized systems commissioning.", "category": "Program Management", "probability": 40, "cost_min": 2_000_000, "cost_expected": 5_000_000, "cost_max": 10_000_000, "notes": "International recruitment program being explored."},
    {"title": "Supply chain disruption — critical equipment", "description": "Global supply chain issues delaying long-lead equipment delivery.", "category": "Program Management", "probability": 35, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Critical path items identified for early procurement."},
    {"title": "Quality management system deficiency", "description": "Quality audits revealing systemic non-conformances requiring program-wide corrective action.", "category": "Program Management", "probability": 30, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Independent quality audit scheduled."},
    {"title": "Document control system overload", "description": "Project information management system struggling with volume of submittals.", "category": "Program Management", "probability": 35, "cost_single": 800_000, "notes": "System upgrade or replacement being evaluated."},
    {"title": "Regulatory approval — safety case", "description": "Safety authority requiring additional safety case documentation before trial running.", "category": "Program Management", "probability": 40, "cost_min": 1_500_000, "cost_expected": 4_000_000, "cost_max": 9_000_000, "notes": "Early engagement with safety regulator recommended."},
    {"title": "Community benefit agreement obligations", "description": "CBA commitments for local hiring and apprenticeships exceeding budget.", "category": "Program Management", "probability": 45, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "Local workforce development program tracking to target."},
    {"title": "Interagency coordination delays", "description": "Multiple government agencies with overlapping jurisdiction causing approval bottlenecks.", "category": "Program Management", "probability": 55, "cost_single": 2_500_000, "notes": "MOU between agencies being negotiated."},
    {"title": "Claims management resource shortage", "description": "Volume of contractor claims exceeding in-house review capacity.", "category": "Program Management", "probability": 50, "cost_min": 1_000_000, "cost_expected": 3_000_000, "cost_max": 7_000_000, "notes": "External claims consultants being engaged."},
    {"title": "Project closeout and defects liability", "description": "Defects rectification at handover taking longer and costing more than planned.", "category": "Program Management", "probability": 60, "cost_min": 3_000_000, "cost_expected": 8_000_000, "cost_max": 18_000_000, "notes": "Defects tracking system being set up."},
]


# ── 50 Mitigations linked to relevant risks ──────────────────────────

MITIGATIONS = [
    # Tunneling
    {"title": "TBM preventive maintenance program", "description": "Comprehensive scheduled maintenance regime for tunnel boring machine components including main bearing, cutterhead, and hydraulic systems.", "notes": "Maintenance windows every 500m of advance.", "link_risk_indices": [0, 7, 24]},
    {"title": "Ground treatment ahead of TBM", "description": "Probe drilling and pre-grouting program to treat poor ground conditions before TBM arrival.", "notes": "Trigger criteria defined for activation.", "link_risk_indices": [1, 2, 12]},
    {"title": "Real-time TBM guidance monitoring", "description": "Enhanced survey and guidance system with automated deviation alerts.", "notes": "Redundant guidance systems specified.", "link_risk_indices": [3, 15]},
    {"title": "Spare segment inventory management", "description": "Maintain buffer stock of precast segments at shaft site to avoid production delays.", "notes": "Two-week buffer stock target.", "link_risk_indices": [4, 18]},
    {"title": "Hyperbaric crew training and certification", "description": "Expanded team of certified hyperbaric workers with ongoing training program.", "notes": "Medical screening every 6 months.", "link_risk_indices": [5, 22]},
    {"title": "Muck disposal contingency sites", "description": "Secure permits for two additional spoil disposal locations.", "notes": "Environmental assessments submitted for both sites.", "link_risk_indices": [6]},
    {"title": "Enhanced ventilation ducting plan", "description": "Oversized ventilation system with redundant fans for extended tunnel drives.", "notes": "Fan procurement on accelerated schedule.", "link_risk_indices": [11, 12]},
    {"title": "Settlement monitoring and response plan", "description": "Automated real-time ground settlement monitoring with defined trigger-action response.", "notes": "InSAR and prism monitoring combined.", "link_risk_indices": [20, 21, 105, 125]},

    # Stations
    {"title": "Station cavern support design review", "description": "Independent peer review of station cavern rock support design by specialist consultant.", "notes": "Review panel includes three international tunnel experts.", "link_risk_indices": [25, 26]},
    {"title": "Platform screen door multi-vendor strategy", "description": "Pre-qualify second PSD supplier to reduce single-source risk.", "notes": "Second supplier identified — technical evaluation in progress.", "link_risk_indices": [27, 158]},
    {"title": "BIM clash detection program", "description": "Weekly automated clash detection runs with mandatory resolution tracking.", "notes": "Clash resolution rate target: 95% within 2 weeks.", "link_risk_indices": [34, 38]},
    {"title": "Station waterproofing quality assurance", "description": "Independent waterproofing inspection with flood testing at each station.", "notes": "Third-party inspector assigned full-time.", "link_risk_indices": [30, 45]},
    {"title": "Fire engineering early engagement", "description": "Fire safety strategy development in parallel with preliminary design, not after.", "notes": "Fire engineer embedded in design team.", "link_risk_indices": [29, 39]},
    {"title": "Station design freeze protocol", "description": "Formal design freeze milestones to prevent late changes and scope growth.", "notes": "Design freeze committee established.", "link_risk_indices": [28, 45, 46]},

    # Utilities
    {"title": "Comprehensive utility survey program", "description": "GPR, vacuum potholing, and CCTV survey of all utilities within 10m of alignment.", "notes": "Survey 60% complete — priority sections first.", "link_risk_indices": [53, 58, 67]},
    {"title": "Utility owner coordination framework", "description": "Formal coordination agreements with all affected utility owners including response time commitments.", "notes": "MOUs signed with power and water — gas and telecom pending.", "link_risk_indices": [50, 51, 55, 61, 62]},
    {"title": "Utility relocation early works package", "description": "Advance contract for critical utility diversions on construction critical path.", "notes": "Early works contract 70% complete.", "link_risk_indices": [50, 52, 65]},
    {"title": "Temporary works design for utility protection", "description": "Robust temporary support and protection measures for retained utilities.", "notes": "Design standards aligned with utility owner requirements.", "link_risk_indices": [54, 60, 64]},
    {"title": "Dewatering management plan", "description": "Comprehensive dewatering strategy with treatment and monitoring protocols.", "notes": "Discharge permit application submitted.", "link_risk_indices": [70, 71]},

    # Design
    {"title": "GBR language independent review", "description": "Legal and technical review of geotechnical baseline report by independent expert.", "notes": "Review to identify ambiguous language before construction procurement.", "link_risk_indices": [75, 76]},
    {"title": "Design interface management system", "description": "Formal design interface register with assigned owners and resolution tracking.", "notes": "200+ interfaces identified — 60% have assigned owners.", "link_risk_indices": [77, 84, 98]},
    {"title": "Constructability review program", "description": "Structured constructability reviews at 30%, 60%, and 90% design milestones.", "notes": "First review complete — 45 actions raised.", "link_risk_indices": [85, 86]},
    {"title": "Climate resilience design review", "description": "Incorporate climate change projections into drainage, ventilation, and structural design.", "notes": "2080 climate scenarios adopted for design.", "link_risk_indices": [87, 88]},
    {"title": "Value engineering governance", "description": "Formal VE identification, approval, and tracking process with risk assessment.", "notes": "VE register established with achievability scoring.", "link_risk_indices": [97, 99]},

    # Geotechnical
    {"title": "Supplementary ground investigation", "description": "Additional boreholes, in-situ testing, and laboratory testing in critical zones.", "notes": "Phase 2 investigation scope approved — mobilization in 4 weeks.", "link_risk_indices": [100, 108, 120]},
    {"title": "Ground treatment trial program", "description": "Full-scale trials of jet grouting and ground freezing before production treatment.", "notes": "Trial locations selected at representative ground conditions.", "link_risk_indices": [113, 121]},
    {"title": "Building condition pre-surveys", "description": "Comprehensive pre-construction surveys of all buildings within zone of influence.", "notes": "800+ properties surveyed — data catalogued in GIS.", "link_risk_indices": [105, 109, 125]},
    {"title": "Geotechnical instrumentation and monitoring", "description": "Extensive monitoring program with automated alerts and defined trigger-action responses.", "notes": "Monitoring specification finalized — installation underway.", "link_risk_indices": [102, 106, 110, 115]},
    {"title": "Dewatering impact assessment", "description": "Numerical groundwater modeling to predict drawdown impacts on surrounding area.", "notes": "3D groundwater model calibrated with pumping test data.", "link_risk_indices": [109, 111]},

    # Community Impacts
    {"title": "Community engagement program", "description": "Proactive engagement including shopfront offices, hotline, newsletters, and regular meetings.", "notes": "Three community offices operational.", "link_risk_indices": [127, 131, 139]},
    {"title": "Construction noise and vibration management", "description": "Comprehensive noise and vibration mitigation measures including barriers, equipment selection, and timing.", "notes": "Noise management plan approved by council.", "link_risk_indices": [128, 141, 148, 143]},
    {"title": "Traffic management optimization", "description": "Adaptive traffic management using real-time monitoring and modeling.", "notes": "Microsimulation model covering 50-block study area.", "link_risk_indices": [133, 129, 137, 142]},
    {"title": "Heritage protection measures", "description": "Building-specific protection plans for all heritage-listed structures.", "notes": "Conservation architect retained for duration of construction.", "link_risk_indices": [130, 138]},
    {"title": "Environmental monitoring and compliance", "description": "Continuous monitoring of dust, noise, water quality, and vibration at site boundaries.", "notes": "Automated monitoring with public-facing dashboard.", "link_risk_indices": [132, 145, 149]},
    {"title": "Business support program", "description": "Financial assistance and marketing support for businesses affected by construction.", "notes": "Small business fund established — applications open.", "link_risk_indices": [126]},

    # System Integration
    {"title": "CBTC supplier progress monitoring", "description": "Embedded owner's engineer at signaling supplier factory to monitor progress.", "notes": "Monthly progress reviews with earned value reporting.", "link_risk_indices": [150, 167]},
    {"title": "Systems integration testing facility", "description": "Dedicated integration lab for testing all system interfaces before field installation.", "notes": "Lab construction 80% complete.", "link_risk_indices": [153, 159, 161, 163]},
    {"title": "Cybersecurity assessment and remediation", "description": "OT cybersecurity program including assessment, design hardening, and testing.", "notes": "Cybersecurity framework adopted — gap assessment complete.", "link_risk_indices": [165, 172]},
    {"title": "ITC schedule recovery plan", "description": "Identify opportunities to advance systems installation and testing in completed sections.", "notes": "Section-by-section ITC plan being developed.", "link_risk_indices": [164, 154]},
    {"title": "EMC design and testing program", "description": "Electromagnetic compatibility design reviews and field testing during installation.", "notes": "EMC consultant embedded in systems design team.", "link_risk_indices": [156, 166]},
    {"title": "Rolling stock-infrastructure interface management", "description": "Formal interface control documents between train and infrastructure systems.", "notes": "ICD register with 150+ interface items.", "link_risk_indices": [151, 158, 170]},

    # Program Management
    {"title": "Land acquisition acceleration", "description": "Parallel negotiation and compulsory acquisition processes for remaining parcels.", "notes": "Legal team augmented with additional property lawyers.", "link_risk_indices": [175]},
    {"title": "Inflation hedging strategy", "description": "Financial instruments and contract mechanisms to mitigate inflation risk.", "notes": "Treasury team evaluating commodity swaps.", "link_risk_indices": [179, 188]},
    {"title": "Dispute resolution framework", "description": "Tiered dispute resolution: project-level negotiation, DRB, arbitration.", "notes": "DRB members selected and empaneled.", "link_risk_indices": [180, 189]},
    {"title": "Schedule risk analysis updates", "description": "Quarterly quantitative schedule risk analysis with Monte Carlo simulation.", "notes": "Schedule model maintained in Primavera P6.", "link_risk_indices": [181, 182]},
    {"title": "Contingency management framework", "description": "Risk-based contingency allocation with monthly drawdown tracking.", "notes": "Contingency by risk category — not block allocation.", "link_risk_indices": [190, 182]},
    {"title": "Multi-contract interface management", "description": "Dedicated interface manager for each major contract boundary.", "notes": "Interface meetings weekly at critical work fronts.", "link_risk_indices": [189, 194]},
    {"title": "Claims management team", "description": "Dedicated claims team for timely assessment and resolution of contractor claims.", "notes": "Claims consultant firm retained on long-term basis.", "link_risk_indices": [198, 180]},
    {"title": "Federal compliance reporting system", "description": "Automated compliance reporting system for federal grant requirements.", "notes": "System configured for FTA reporting requirements.", "link_risk_indices": [176, 184]},
    {"title": "Workforce development program", "description": "Training and apprenticeship program to develop local systems commissioning workforce.", "notes": "Partnership with local technical college established.", "link_risk_indices": [191, 196]},
]


def main():
    client = httpx.Client(timeout=30)

    # Get or create register
    registers = client.get(f"{BASE}/registers").json()
    if registers:
        reg_id = registers[0]["id"]
        # Delete existing risks to start fresh
        existing_risks = client.get(f"{BASE}/registers/{reg_id}/risks").json()
        for r in existing_risks:
            client.delete(f"{BASE}/risks/{r['id']}")
        existing_mits = client.get(f"{BASE}/registers/{reg_id}/mitigations").json()
        for m in existing_mits:
            client.delete(f"{BASE}/mitigations/{m['id']}")
        # Update register name
        client.patch(f"{BASE}/registers/{reg_id}", json={"name": "Metro Line 3 Extension \u2014 Underground Transit"})
        print(f"Cleared existing register {reg_id}")
    else:
        reg = client.post(f"{BASE}/registers", json={"name": "Metro Line 3 Extension \u2014 Underground Transit"}).json()
        reg_id = reg["id"]
        print(f"Created register: {reg_id}")

    # Create risks
    created_risks = []
    for i, risk_data in enumerate(RISKS):
        r = client.post(f"{BASE}/registers/{reg_id}/risks", json=risk_data).json()
        created_risks.append(r)
        if (i + 1) % 25 == 0:
            print(f"  Created {i + 1}/{len(RISKS)} risks ({r['display_id']})")
    print(f"  Created {len(created_risks)} risks total")

    # Create mitigations with risk links
    created_mits = []
    for mit_data in MITIGATIONS:
        link_indices = mit_data.pop("link_risk_indices")
        m = client.post(f"{BASE}/registers/{reg_id}/mitigations", json=mit_data).json()
        created_mits.append(m)

        for risk_idx in link_indices:
            if risk_idx < len(created_risks):
                risk_id = created_risks[risk_idx]["id"]
                client.post(f"{BASE}/mitigations/{m['id']}/risks/{risk_id}")

    print(f"  Created {len(created_mits)} mitigations with risk links")

    print(f"\nDone! {len(created_risks)} risks and {len(created_mits)} mitigations seeded.")
    print("Refresh your browser to see the data.")


if __name__ == "__main__":
    main()
