"""initial schema

Revision ID: 423037571c55
Revises: 
Create Date: 2026-02-12 06:11:57.838708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423037571c55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitigations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('register_id', sa.Text(), nullable=False),
    sa.Column('display_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register_id', 'display_id')
    )
    op.create_table('risks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('register_id', sa.Text(), nullable=False),
    sa.Column('display_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('cost_single', sa.Float(), nullable=True),
    sa.Column('cost_min', sa.Float(), nullable=True),
    sa.Column('cost_expected', sa.Float(), nullable=True),
    sa.Column('cost_max', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register_id', 'display_id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('register_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggregate_expected_cost', sa.Float(), nullable=True),
    sa.Column('aggregate_mean', sa.Float(), nullable=True),
    sa.Column('aggregate_std_dev', sa.Float(), nullable=True),
    sa.Column('aggregate_p10', sa.Float(), nullable=True),
    sa.Column('aggregate_p20', sa.Float(), nullable=True),
    sa.Column('aggregate_p30', sa.Float(), nullable=True),
    sa.Column('aggregate_p40', sa.Float(), nullable=True),
    sa.Column('aggregate_p50', sa.Float(), nullable=True),
    sa.Column('aggregate_p60', sa.Float(), nullable=True),
    sa.Column('aggregate_p70', sa.Float(), nullable=True),
    sa.Column('aggregate_p80', sa.Float(), nullable=True),
    sa.Column('aggregate_p90', sa.Float(), nullable=True),
    sa.Column('aggregate_p95', sa.Float(), nullable=True),
    sa.Column('risk_count', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_comments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('risk_id', sa.Text(), nullable=False),
    sa.Column('column_key', sa.Text(), nullable=False),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_mitigations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('risk_id', sa.Text(), nullable=False),
    sa.Column('mitigation_id', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mitigation_id'], ['mitigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'mitigation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_mitigations')
    op.drop_table('cell_comments')
    op.drop_table('snapshots')
    op.drop_table('risks')
    op.drop_table('mitigations')
    op.drop_table('registers')
    # ### end Alembic commands ###
